skill_library = [
   "python", "pyhton", "pythn",
    "javascript", "js", "java script", "javscript",
    "typescript", "ts", "type script", "typescirpt",
    "react", "react.js", "reactjs", "react js",
    "next.js", "nextjs", "next js",
    "node.js", "nodejs", "node js",
    "express", "express.js", "expressjs",
    "html", "html5",
    "css", "css3",
    "tailwind css", "tailwindcss", "tailwind",
    "java",
    "c", "c++", "cpp", "c plus plus",
    "c#", "c sharp", "csharp",
    "sql", "mysql", "postgresql", "postgres", "sqlite",
    "mongodb", "mongo db", "mongoose",
    "fastapi", "fast api",
    "flask", "django",
    "git", "github", "git hub",
    "rest api", "rest apis", "restful api", "restful apis", "rest",
    "docker", "kubernetes",
    "aws", "amazon web services", "azure", "google cloud", "gcp",
    "numpy", "pandas",
    "scikit-learn", "scikit learn", "sklearn",
    "tensorflow", "tensor flow",
    "pytorch", "py torch",
    "machine learning", "ml",
    "artificial intelligence", "ai",
    "natural language processing", "nlp",
    "linux", "unix", "bash", "shell scripting",
    "graphql", "redis", "firebase",
    "spring boot", "springboot",
    ".net", "asp.net",
    "ruby", "ruby on rails",
    "php", "laravel",
    "go", "golang",
    "rust", "swift", "kotlin"
]