import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { getSession } from "@/lib/auth/auth"
import connectDB from "@/lib/db"
import Profile from "@/lib/models/profile"
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function NavbarWithProfile() {
  const session = await getSession()

    let profile = null

    if (session?.user) {
        await connectDB()
        profile = await Profile.findOne({ userId: session.user.id }).lean()
    }
    return <Navbar profile={profile ? JSON.parse(JSON.stringify(profile)) : null} />
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div className="h-16" />}>
          <NavbarWithProfile />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
